name: example
on: push
jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - run: echo hello world
  
  setUpContainer:
    needs: greeting
    runs-on: ubuntu-latest
    container: rootproject/root:6.26.10-conda

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Install ROOT
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: env
          create-args: root
      
      - name: Install cvmfx
        run: |
          yum install -y https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest.noarch.rpm
          yum install -y cvmfs

        


