name: example
on: push
jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - run: echo hello world
  
  setUpContainer:
    needs: greeting
    runs-on: ubuntu-latest
    container: rootproject/root:6.26.10-conda

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Install ROOT
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: env
          create-args: root
      
      - name: Install cvmfx
        - run: |
              sudo yum install https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest.noarch.rpm
              sudo yum install -y cvmfs
        



  cmssw_compile:
    tags:
      - cvmfs
    variables:
      CMS_PATH: /cvmfs/cms.cern.ch
      CMSSW_RELEASE: CMSSW_10_6_8_patch1
    script:
      - shopt -s expand_aliases
      - set +u && source ${CMS_PATH}/cmsset_default.sh; set -u
      - cmsrel ${CMSSW_RELEASE}
      - cd ${CMSSW_RELEASE}/src
      - cmsenv
      - mkdir -p AnalysisCode
      - cp -r "${CI_PROJECT_DIR}/ZPeakAnalysis" "${CMSSW_BASE}/src/AnalysisCode/"
      - scram b

