name: example
on: push
jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - run: echo hello world


  build_skim:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: Install ROOT
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: env
          create-args: root
      - name: build
        run: |
          COMPILER=$(root-config --cxx)
          FLAGS=$(root-config --cflags --libs)
          $COMPILER -g -O3 -Wall -Wextra -Wpedantic -o skim skim.cxx $FLAGS
      - uses: actions/upload-artifact@v4
        with:
          name: 6.26.10-conda
          path: skim


  skim:
    needs: build_skim
    runs-on: ubuntu-latest
    container: rootproject/root:6.26.10-conda
    steps:
        - name: checkout repository
          uses: actions/checkout@v4
        
        - uses: actions/download-artifact@v4
          with:
            name: skim6.26.10-conda

        - name: skim
          run: |
            chmod +x ./skim
            ./skim