name: example
on: push
jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - run: echo hello world
  
  setUpContainer:
    needs: greeting
    runs-on: ubuntu-latest
    container: rootproject/root:6.26.10-conda

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Install ROOT
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: env
          create-args: root
      
      - name: Install cvmfx
        run: |
          sudo apt-get install curl
          
          curl https://ecsft.cern.ch/dist/cvmfs/cvmfs-2.11.2/cvmfs-service-2.11.2-1.x86_64.docker.tar.gz | docker load
          docker run -d --rm \
            -e CVMFS_CLIENT_PROFILE=single \
            -e CVMFS_REPOSITORIES=sft.cern.ch,... \
            --cap-add SYS_ADMIN \
            --device /dev/fuse \
            --volume /cvmfs:/cvmfs:shared \
            cvmfs/service:2.11.2-1

        


