name: example
on: push
jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - run: echo hello world
  
  cmssw_compile:
    tags:
      - cvmfs
    variables:
      CMS_PATH: /cvmfs/cms.cern.ch
      CMSSW_RELEASE: CMSSW_10_6_8_patch1
    script:
      - shopt -s expand_aliases
      - set +u && source ${CMS_PATH}/cmsset_default.sh; set -u
      - cmsrel ${CMSSW_RELEASE}
      - cd ${CMSSW_RELEASE}/src
      - cmsenv
      - mkdir -p AnalysisCode
      - cp -r "${CI_PROJECT_DIR}/ZPeakAnalysis" "${CMSSW_BASE}/src/AnalysisCode/"
      - scram b

